### ISSUE TITLE
如何确认插件是否生效？

### ISSUE THREAD

**Issue by Sherryme** [coder-xiaotian/swc-useclient#3]
我在 https://github.com/ant-design/ant-design/issues/38555#issuecomment-1628102394 中见到了您给的解决方案，我尝试让 antd 的`Layout.Header`组件能够正常使用，但是我失败了，它仍然会报错`Error: Cannot access .Header on the server. You cannot dot into a client module from a server component. You can only pass the imported name through.`。

复现仓库：https://github.com/Sherryme/swc-useclient-demo

**Comment by Sherryme** [comment]
经过测试，单纯使用`Layout`的时候，插件是生效了的，但是似乎无法处理`Layout.Header`这一类子组件。

**Comment by coder-xiaotian** [comment]
临时解决办法 import {Header} from 'antd/es/layout/layout'
Layout.Header这种用法没考虑到，因为插件内部是检查路径是否包括"antd"，直接用Layout.Header，内部导入语句是import {Header} from "./layout"，不包括antd路径

**Comment by Sherryme** [comment]
感谢，不过经尝试发现，还有一种类似组件的东西也会出现这类问题，不知该如何导入才能使插件对其生效？

比如下面的`theme.darkAlgorithm`同样会出现：`Error: Cannot access .darkAlgorithm on the server. You cannot dot into a client module from a server component. You can only pass the imported name through.`

```typescript
import {ConfigProvider, theme} from 'antd';

<ConfigProvider
    theme={{
        algorithm: theme.darkAlgorithm,
    }}
>
    ...
</ConfigProvider>
```

----

尝试导入`import theme_darkAlgorithm from 'antd/es/theme/themes/dark';`发现可行，但是发现其样式不会对使用`import { Footer } from 'antd/es/layout/layout';`导入的`Footer`生效，如何解决？

https://github.com/Sherryme/swc-useclient-demo/commit/fe7ee8027c27d5cb3164081c8b75a159fcb948ec 使用了插件 ：

![image](https://github.com/coder-xiaotian/swc-useclient/assets/18429499/650383ba-58aa-4e2c-b6ef-f2fffbf9af70)

https://github.com/Sherryme/swc-useclient-demo/commit/abcc3df9f489cd025e4de9d90c12652e65634b65 禁用了插件 ：

![image](https://github.com/coder-xiaotian/swc-useclient/assets/18429499/818b8f9e-0bc1-4564-8fe5-dd4a61cbae77)

**Comment by Sherryme** [comment]
还有，`@ant-design/icons`的`createFromIconfontCN`也无法使用，报错`Error: Attempted to call createFromIconfontCN() from the server but createFromIconfontCN is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.`

```typescript
import { createFromIconfontCN } from "@ant-design/icons";

const IconFont = createFromIconfontCN({
    scriptUrl: '//at.alicdn.com/t/c/xxxxxx.js',
});
```

**Comment by coder-xiaotian** [comment]
> ```ts
> import { createFromIconfontCN } from "@ant-design/icons";
> 
> const IconFont = createFromIconfontCN({
>     scriptUrl: '//at.alicdn.com/t/c/xxxxxx.js',
> });
> ```

错误提示上说得比较明确了，createFromIconfontCN只能在客户端组件使用，这不是use-client插件的问题，你应该这么改
```js
"use client"
import { createFromIconfontCN } from "@ant-design/icons";

const IconFont = createFromIconfontCN({
    scriptUrl: '//at.alicdn.com/t/c/xxxxxx.js',
});
```

**Comment by coder-xiaotian** [comment]
> 

Provider只能在客户端组件里面使用，这点在[next.js文档](https://nextjs.org/docs/getting-started/react-essentials#rendering-third-party-context-providers-in-server-components)有说明的，另外你也可以参考[我的代码](https://github.com/coder-xiaotian/layzy-cut/blob/main/src/app/providers.tsx)
